### ISSUE TITLE
How to obtain the CSV file corresponding to clinical_path？

### ISSUE THREAD

**Issue by wadegrc** [mahmoodlab/mamba#1]
Thank you for your outstanding work. I am using your method on the [OTLS](https://www.cancerimagingarchive.net/collection/pca_bx_3dpathology/) dataset, but in the third step, I need to specify the clinical_path in config.MIL.yaml. Where can I obtain csv file. I couldn't find the csv file in [OTLS](https://www.cancerimagingarchive.net/collection/pca_bx_3dpathology/)

**Comment by andrewsong90** [comment]
Hi @wadegrc,

The corresponding clinical file can be found in https://www.cancerimagingarchive.net/collection/pca_bx_3dpathology/
There is **Clinical Data** csv file under **Data Access**. There you can find both the binary status and the actual followup dates.
