### ISSUE TITLE
How to run this algorithm on the PCa_Bx_3Dpathology dataset

### ISSUE THREAD

**Issue by Dylan-H-Wang** [mahmoodlab/mamba#2]
Hi,

Thank you for the outstanding work! I am trying to use this algorithm to replicate the results on PCa_Bx_3Dpathology dataset. However, it seems like the data loader is specifically written for MicroCT data? Could you please indicate how to run [Step 1: Tissue segmentation & patching](https://github.com/mahmoodlab/TriPath?tab=readme-ov-file#step-1-tissue-segmentation--patching) on the PCa_Bx_3Dpathology dataset?

Thank you for the time and help!
Kind regards,
Dylan

**Comment by andrewsong90** [comment]
Hi Dylan,

The dataloader is not written specifically for any dataset - It should be able to cater to both microCT and OTLS, with the only setting change supplied by keyword arguments or csv files.

For instance, the provided [csv](https://github.com/mahmoodlab/TriPath/blob/main/csv/process_list_seg.csv) file is an example from OTLS. For OTLS, I also recommend using `--thresh_mode global`

Hope this helps!

**Comment by Dylan-H-Wang** [comment]
Hi Andrew,

Thank you for the reply!

Sorry for the unclear description of the question. Here is what I have done so far
1. Download the data from  https://www.cancerimagingarchive.net/collection/pca_bx_3dpathology as you mentioned in the paper. 
2. Run the [Step 1: Tissue segmentation & patching](https://github.com/mahmoodlab/TriPath?tab=readme-ov-file#step-1-tissue-segmentation--patching)

However, it seems like the [ThreeDimImage](https://github.com/mahmoodlab/TriPath/blob/02d0a738fb1573b7b76416f7fb998b43fd875c3d/preprocess/wsi_core/ThreeDimImage.py#L23) using [read_img](https://github.com/mahmoodlab/TriPath/blob/02d0a738fb1573b7b76416f7fb998b43fd875c3d/preprocess/wsi_core/img_utils.py#L14) function is deal with metadata with `.dat` extension and image files with `.dcm` or compatible with `opencv`.
But the raw data contained in `pca_bx_3dpathology` is `h5py` file with `.xml` file as the metadata.

Did I miss anything essential step to preprocess the data?

Thank you!
