### ISSUE TITLE
Data processing for PCa_Bx_3Dpathology dataset

### ISSUE THREAD

**Issue by Dylan-H-Wang** [mahmoodlab/mamba#3]
Hi,

Thank you for the wonderful work!

I am still confused about running the algorithm on the [PCa_Bx_3Dpathology](https://www.cancerimagingarchive.net/collection/pca_bx_3dpathology/) dataset.

This is what I have done so far
1. Download the data from  https://www.cancerimagingarchive.net/collection/pca_bx_3dpathology as you mentioned in the paper. The WSI data in the dataset is saved as a `HDF5` file giving two channel information (nuclei and cyto).
2. Run the [Step 1: Tissue segmentation & patching](https://github.com/mahmoodlab/TriPath?tab=readme-ov-file#step-1-tissue-segmentation--patching)

It will throw error messages. I tried to debug and find some questions:

1. It seems like the [ThreeDimImage](https://github.com/mahmoodlab/TriPath/blob/02d0a738fb1573b7b76416f7fb998b43fd875c3d/preprocess/wsi_core/ThreeDimImage.py#L23) using [read_img](https://github.com/mahmoodlab/TriPath/blob/02d0a738fb1573b7b76416f7fb998b43fd875c3d/preprocess/wsi_core/img_utils.py#L14) function is deal with metadata with `.dat` extension and image files with `.dcm` or compatible with `opencv`. But the raw data contained in `pca_bx_3dpathology` is `h5py` file with `.xml` file as the metadata. How did you preprocess the raw data?
2. You mentioned in the paper that _"we replicate the nuclear channel data across the first two channels and set the eosin channel as the third"_. Does it also applied when you are applying segmentation for the image? Since I have checked the segmentation implementation in [SerialTwoDimImage](https://github.com/mahmoodlab/TriPath/blob/main/preprocess/wsi_core/SerialTwoDimImage.py), it was implemented through `opencv` in [_getBinarizedImage()](https://github.com/mahmoodlab/TriPath/blob/02d0a738fb1573b7b76416f7fb998b43fd875c3d/preprocess/wsi_core/SerialTwoDimImage.py#L985) and should only applied for RGB or grayscale images. Did you convert the two-channel (nuclei and eosin) to RGB first before segmentation?
3. In [process_list_seg.csv](https://github.com/mahmoodlab/TriPath/blob/main/csv/process_list_seg.csv), it only provides settings for `c001-A`, does it apply to all other files, i.e., `c001-B`, ..., `c050-E`.

Thank you!

**Comment by andrewsong90** [comment]
Hi @Dylan-H-Wang,

I am currently on vacation - Let me check these points when I get back next week

**Comment by Dylan-H-Wang** [comment]
@andrewsong90 
Thank you for the reply. Take your time and have a good vacation!

**Comment by andrewsong90** [comment]
Hi @Dylan-H-Wang,

Super sorry for the delay - There were few personal issues I had to deal with.
1. So what I did for these datsets are covert them to .tiff images - The 3D image would then be treated as a stack of 2D tiff image stacks. DCM was put in there in case we wanted to expand this framework to radiology images, which are usually in DICOM format.

2. For the preprocessing step (which includes segmentation), this is not the case. What happens is We take average across channels to get single-channel information (grayscale) and use the threshold on this single-channel. This directly replicates what is being done in 2D pathology image segmentation (as used in CLAM repository).

3. Yes, that was intentional, because the .csv file was more of an example. If you want, I can release the actual .csv files I had used for this.

Let me know if this helps,
Andrew

**Comment by Dylan-H-Wang** [comment]
Hi @andrewsong90,

Thank you for the detailed explanations! Here some follow-up questions:

1. If possible, could you please also release the actual `csv` files for `process_list_seg.csv` and `process_list_seg.csv`?

2. In terms of preprocessing step

a) The workflow in the paper is grayscale -> median-blur -> binarize
> Images in the remaining stack are then converted to grayscale color space, median-blurred to suppress edge artifacts, and binarized with modality-specific thresholds.

However, the workflow in [_getBinarizedImage()](https://github.com/mahmoodlab/TriPath/blob/02d0a738fb1573b7b76416f7fb998b43fd875c3d/preprocess/wsi_core/SerialTwoDimImage.py#L985) is inconsistent which does median-blur -> grayscale -> binarize
https://github.com/mahmoodlab/TriPath/blob/122b6ad8441c66c880f914934b00128ceacc704a/preprocess/wsi_core/SerialTwoDimImage.py#L980-L991

b) Assuming 2D slice is saved with (CH1, CH2, CH3), where CH1=CH2=nuclean_channel, and CH3=eosin_channel. You were indicating "_We take average across channels to get single-channel information (grayscale)_". However, the workflow in [_getBinarizedImage()](https://github.com/mahmoodlab/TriPath/blob/02d0a738fb1573b7b76416f7fb998b43fd875c3d/preprocess/wsi_core/SerialTwoDimImage.py#L985) is using `cv2.cvtColor(img_med, cv2.COLOR_RGB2GRAY)` to combine (CH1, CH2, CH3). This `opencv` algorithm formular is `Y = 0.299 R + 0.587 G + 0.114 B` instead of `Y = (R + G + B)/3`?

Please help to clarify when you are available. Thank you!

**Comment by andrewsong90** [comment]
Hi @Dylan-H-Wang,

1. I just pushed the new `process_list_seg.csv` file - As for the thresholds they should all be same across the samples, with the exception of the `clip_max` value, some of which are 3000. When I manually inspected the images, some of the samples were of low signal, hence the lower clip_max assigned to these samples.

2. Thanks for taking a detailed look - It seems there is a small discrepancy between what is in the paper and the actual code. Whatever is in the code would the steps I used to preprocess the data.

Thank you again for your interest!

**Comment by Dylan-H-Wang** [comment]
Hi @andrewsong90,

Thank you so much for the detailed explanation and patience! BTW, could you please also update `process_list_heatmap.csv` file if possible?

Also, in the updated `process_list_seg.csv`, it appears that only a subset of the slides was used to create patches, and 1 biopsy from each subject was marked as not to be processed (i.e., `process = 0`). Could you clarify why this decision was made?

Again, really appreciate your amazing and solid works!
