### ISSUE TITLE
NotImplementedError: Not implemented for normalization OTLS

### ISSUE THREAD

**Issue by Dylan-H-Wang** [mahmoodlab/mamba#4]
Hi,

When I tried to run [Step 2: extract features](https://github.com/mahmoodlab/TriPath?tab=readme-ov-file#step-2-feature-extraction) on the OTLS dataset, it will throw an error `NotImplementedError: Not implemented for normalization OTLS`.

I have located the bug is in the [data/transforms.py/Normalize](https://github.com/mahmoodlab/TriPath/blob/02d0a738fb1573b7b76416f7fb998b43fd875c3d/data/transforms.py#L146). When the `data_mode` is set to `OTLS`, it will throw this error since it only accept mode `CT` or `HE`.

**Comment by andrewsong90** [comment]
@Dylan-H-Wang 

Thank you so much! Yes, I will correct this in the next iteration of the code update. The intention was to just use HE mode for OTLS as well (There was an error in cleaning up the code)
