### ISSUE TITLE
Release of the weights (OTLS data)

### ISSUE THREAD

**Issue by ghaeflig** [mahmoodlab/mamba#6]
Hi,

First, congrats for your amazing work. I wanted to know if it is possible that you release the weights of the model for OTLS data as it is open-source data. I am even more interested in the weights of the model that you used on the transformed OTLS data that mimic microCT for the cross-modal evaluation. If not, I will try to replicate the training.

Thank you and have a great day,

Garance

**Comment by andrewsong90** [comment]
Hi @ghaeflig 

Thank you for your interest in the work. Unfortunately, it might be hard to release the model weights at this point. I will see if in the next version I can release the models trained on a bigger cohort. I tried to write all the hyperparameters I used for training, so hope that helps!

Best,
